### ISSUE TITLE
[QUESTION] Why is Physics missing?

### ISSUE THREAD

**Issue by DataJuggler** [NVIDIA-Omniverse/kit-app-template#28]
### Question

I followed the instructions and ran the app, and selected USD Composer option. The app launches, but Physics is missing from both Preferences and the Create and Add menus.

What happened to Physics? Physics is the main thing I use Omniverse for.

**Comment by Administrators-0001** [comment]
I'm having problems with my device's web IDs and haven't loaded. Nvidia from the beginning it seems that there is a hack of my device can you trace the device ID to make sure

+966566200911

بتاريخ ٠٥‏/١٠‏/٢٠٢٤ ١٢:٣٧ م، كتب Data Juggler ***@***.***>:

Question

I followed the instructions and ran the app, and selected USD Composer option. The app launches, but Physics is missing from both Preferences and the Create and Add menus.

What happened to Physics? Physics is the main thing I use Omniverse for.

Additional Context

No response

**Comment by DataJuggler** [comment]
Thanks for the reply. Sorry to ask this in more than one place. I will try this over the weekend.

**Comment by SchultzC** [comment]
There was a delay in publishing some of the extensions.  Physx 106.2.0 was one such extension.  The issue should now be resolved (without requiring a version lock).  Please reopen this issue if you have any other problems.

**Comment by DataJuggler** [comment]
I just cloned the repo today, and Physic was not included. Do I still have to run the instructions where I set the version 6.1.7?

Why is the Extension Manager missing also?

**Comment by ericcraft-mh** [comment]
> I just cloned the repo today, and Physics was not included. Do I still have to run the instructions where I set the version 6.1.7?
> 
> Why is the Extension Manager missing also?

Physx and the Extension Manager are not included by default. Use `launch -d` then enable extension manager on autoload same with physx bundle.

**Comment by DataJuggler** [comment]
OK, the -d showed the Extension Manager. I still don't see Physics as an option on menus. Is there something I need to do?

Thanks

**Comment by SchultzC** [comment]
@ericcraft-mh is correct.  Niether of these things are enabled by default in the Composer template.  Looks like you have the extension manager now.

To add omni.physx.bundle in a persistent way to your application add:

`omni.physx.bundle = {}` 

to the [dependencies] section of the `.kit` file located in `source/apps` and rebuild the application.

**Comment by DataJuggler** [comment]
That worked. I am going to make a video about this so I don't forget. Thanks

**Comment by DataJuggler** [comment]
Last question and I will leave you alone. How do I get the Array tool to show up? Is there a list of all the extension names somewhere so I can which ones I need to add?

**Comment by DataJuggler** [comment]
I figured out the Array. I will try adding it the same was as Physics. 

Was surprised to see a message Physics can't run with Fabric. That was the magic of Fabric, it enabled Physics to handle large amounts of objects. Is there a reason they don't work together anymore.

Thanks again.
